name: easy_stripe_payment
description: "A Flutter package that provides simple and ready stripe payment method."
version: 3.0.8
homepage: https://github.com/Just4prog/easy_stripe_payment

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^11.4.0
  dio: ^5.8.0+1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

